import Navbar from '@/components/Navbar'
import Head from 'next/head'
import Image from 'next/image'

export default function Home() {
  const daysUntilWedding = () => {
    const today = new Date()
    const weddingDate = new Date("09/02/2023")
    const timeDiff = weddingDate.getTime() - today.getTime()
    return Math.ceil(timeDiff / (1000 * 3600 * 24))
  }

  return (
    <>
      <Head>
        <title>Gabriel & Nayeli Wedding | Boda de Gariel y Nayeli</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Navbar/>
        <div className="container mx-auto px-8">
          <div className="flex justify-between items-center">
            <div className="flex flex-col justify-start lg:justify-around items-center py-12 lg:py-0 px-4 lg:px-0 lg:w-1/2 h-full lg:h-[75vh]">
              <div className="flex flex-col justify-center items-center space-y-8 px-12">
                <p className="p1 text-center">We’re getting married! And we are so excited for you to celebrate with us, in just <strong>{daysUntilWedding()} days!</strong></p>
                <hr className="w-16 border-moss-300 border-t-2 border-b-2 rounded"/>
                <p className="p1 text-center">¡Nos vamos a casar! Con muchísima emoción, te esperamos en <strong>{daysUntilWedding()} días!</strong></p>
              </div>
              <div className="flex flex-col justify-around items-center mt-16 lg:mt-0">
                <div className="flex flex-col justify-center items-center">
                  <img src="plant.svg" />
                  <h2 className='text-center font-serif'>San Antonio, TX</h2>
                  <p className='text-center p1'>Septembet 1-2, 2023</p>
                </div>
                <button className="mt-8 primary font-serif">RSVP</button>
              </div>
            </div>``
            <div className=" hidden lg:flex flex-col justify-center items-center w-1/2 h-[75vh] bg-[url('/index-main.png')] bg-contain bg-no-repeat bg-center"/> 
          </div>
        </div>
      </main>
    </>
  )
}